clusterGroup:
  name: hub

  namespaces:
    - hello-world

  projects:
    - hello-world

  applications:
    hello-world:
      name: hello-world
      namespace: hello-world
      project: hello-world
      path: charts/all/hello-world
